// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucbjrinnzhemcbdekbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y2JqcmlubnpoZW1jYmRla2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTA5NDIsImV4cCI6MjA2NTk2Njk0Mn0.Bc0AbdJvRhjVq1JhWvC_6o3GHplol62AIvIyIysziQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);